
import asyncio
import json
import urllib.error
import urllib.request
from abc import ABC, abstractmethod
from typing import Sequence

from src.helpers.config import Settings
from src.models import SearchHit


class LLMProvider(ABC):
    provider_name: str = "llm"

    @abstractmethod
    async def generate_answer(
        self,
        query: str,
        hits: Sequence[SearchHit],
        settings: Settings,
    ) -> str:
        raise NotImplementedError


class RetrievalSummaryLLMProvider(LLMProvider):
    provider_name = "summary"

    async def generate_answer(
        self,
        query: str,
        hits: Sequence[SearchHit],
        settings: Settings,
    ) -> str:
        if not hits:
            return (
                f"No strong match was found for '{query}'. "
                "Add more raw CVs or job descriptions and call /api/ingest to refresh the index."
            )

        lines = [f"Bootstrap retrieval result for: {query}", "", "Top matches:"]
        for hit in hits:
            lines.append(f"{hit.rank}. {hit.source} (score={hit.score:.3f})")
            lines.append(f"   {hit.excerpt}")

        lines.extend(
            [
                "",
                "This answer is generated by the bootstrap retriever. The next implementation slice will replace it with vector search and an LLM provider.",
            ]
        )
        return "\n".join(lines)


class OllamaLLMProvider(LLMProvider):
    provider_name = "ollama"

    def __init__(self, base_url: str, model_name: str, timeout_seconds: int = 90) -> None:
        self.base_url = base_url.rstrip("/")
        self.model_name = model_name
        self.timeout_seconds = timeout_seconds

    async def generate_answer(
        self,
        query: str,
        hits: Sequence[SearchHit],
        settings: Settings,
    ) -> str:
        context = "\n\n".join(
            f"[{hit.rank}] {hit.source}: {hit.excerpt}" for hit in hits[: settings.max_context_chunks]
        )
        if not context:
            return (
                f"No strong match was found for '{query}'. "
                "Add more raw CVs or job descriptions and call /api/ingest to refresh the index."
            )

        prompt = (
            "You are a retrieval-augmented assistant for candidate-job matching. "
            "Answer only from the provided context. If the context is insufficient, say so clearly.\n\n"
            f"Question: {query}\n\n"
            f"Context:\n{context}\n\nAnswer:"
        )
        try:
            return await asyncio.to_thread(self._generate_sync, prompt)
        except Exception:
            return await RetrievalSummaryLLMProvider().generate_answer(query, hits, settings)

    def _generate_sync(self, prompt: str) -> str:
        payload = json.dumps(
            {
                "model": self.model_name,
                "prompt": prompt,
                "stream": False,
                "options": {"temperature": 0.2, "num_ctx": 1024},
            }
        ).encode("utf-8")
        request = urllib.request.Request(
            f"{self.base_url}/api/generate",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(request, timeout=self.timeout_seconds) as response:
            body = json.loads(response.read().decode("utf-8"))
        return str(body.get("response", "")).strip()


def create_llm_provider(settings: Settings) -> LLMProvider:
    if settings.llm_provider.lower() == "ollama":
        return OllamaLLMProvider(
            base_url=settings.ollama_base_url,
            model_name=settings.llm_model,
        )
    return RetrievalSummaryLLMProvider()# TIP: Initialize package exports here.
